name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main00" ]

env:
  CARGO_TERM_COLOR: always
  #SHUTTLE_API: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: install shuttle
      run: cargo install cargo-shuttle
    - name: Run Check Create Project
      run: cargo  shuttle init cch23-smile921 --create-env --name cch23-smiles --template axum --api-key ${{ secrets.SHUTTLE_API_KEY }}
